name: TestingLibrary

on: [ push ]

jobs:
  testingLibrary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm i
      - run: npm start & 
      - run: npm test